/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgeThresholdRouteImport } from './routes/age-threshold'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SeniorsRouteImport } from './routes/seniors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeThresholdRoute = AgeThresholdRouteImport.update({
  id: '/age-threshold',
  path: '/age-threshold',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorsRoute = SeniorsRouteImport.update({
  id: '/seniors',
  path: '/seniors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age-threshold': typeof AgeThresholdRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seniors': typeof SeniorsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age-threshold': typeof AgeThresholdRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seniors': typeof SeniorsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age-threshold': typeof AgeThresholdRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seniors': typeof SeniorsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age-threshold'
    | '/analytics'
    | '/benefits'
    | '/dashboard'
    | '/eligibility'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/seniors'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age-threshold'
    | '/analytics'
    | '/benefits'
    | '/dashboard'
    | '/eligibility'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/seniors'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/age-threshold'
    | '/analytics'
    | '/benefits'
    | '/dashboard'
    | '/eligibility'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/seniors'
    | '/settings'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeThresholdRoute: typeof AgeThresholdRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BenefitsRoute: typeof BenefitsRoute
  DashboardRoute: typeof DashboardRoute
  EligibilityRoute: typeof EligibilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SeniorsRoute: typeof SeniorsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-threshold': {
      id: '/age-threshold'
      path: '/age-threshold'
      fullPath: '/age-threshold'
      preLoaderRoute: typeof AgeThresholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seniors': {
      id: '/seniors'
      path: '/seniors'
      fullPath: '/seniors'
      preLoaderRoute: typeof SeniorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeThresholdRoute: AgeThresholdRoute,
  AnalyticsRoute: AnalyticsRoute,
  BenefitsRoute: BenefitsRoute,
  DashboardRoute: DashboardRoute,
  EligibilityRoute: EligibilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SeniorsRoute: SeniorsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
